//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/gamepadControler.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GamepadControler : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GamepadControler()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""gamepadControler"",
    ""maps"": [
        {
            ""name"": ""gamecontroler"",
            ""id"": ""2899e82f-18b9-41df-818f-48ac85a989a3"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""d38a9421-9906-431c-af34-ab39ce3f82e3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""9c032f41-9227-4281-9b99-8bc0ccbd35ec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShootRight"",
                    ""type"": ""Button"",
                    ""id"": ""b07dd39e-7210-4266-b310-e83d18519ef8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShootLeft"",
                    ""type"": ""Button"",
                    ""id"": ""c53c95f4-7555-478f-be16-24095d23734f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""54a1c2a2-0a8d-4a6d-9394-76996f8dc684"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""675ab9e7-2358-448a-989c-8e46cdc26217"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e8b2163-d0cb-450a-999c-44b6f1dd6437"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShootRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a6c819f-024d-462c-81a9-eb78933e39b3"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShootLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ClavierSouris"",
            ""id"": ""5a2b26ca-04fa-4b02-96ef-f4ab1a32ec3a"",
            ""actions"": [
                {
                    ""name"": ""FoudrePouvoir"",
                    ""type"": ""Button"",
                    ""id"": ""b1207483-db62-48cc-8208-c574ac31d61a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""10dff2dd-50fd-4f3a-9b58-e155a6d98714"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FoudrePouvoir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // gamecontroler
        m_gamecontroler = asset.FindActionMap("gamecontroler", throwIfNotFound: true);
        m_gamecontroler_Move = m_gamecontroler.FindAction("Move", throwIfNotFound: true);
        m_gamecontroler_Jump = m_gamecontroler.FindAction("Jump", throwIfNotFound: true);
        m_gamecontroler_ShootRight = m_gamecontroler.FindAction("ShootRight", throwIfNotFound: true);
        m_gamecontroler_ShootLeft = m_gamecontroler.FindAction("ShootLeft", throwIfNotFound: true);
        // ClavierSouris
        m_ClavierSouris = asset.FindActionMap("ClavierSouris", throwIfNotFound: true);
        m_ClavierSouris_FoudrePouvoir = m_ClavierSouris.FindAction("FoudrePouvoir", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // gamecontroler
    private readonly InputActionMap m_gamecontroler;
    private IGamecontrolerActions m_GamecontrolerActionsCallbackInterface;
    private readonly InputAction m_gamecontroler_Move;
    private readonly InputAction m_gamecontroler_Jump;
    private readonly InputAction m_gamecontroler_ShootRight;
    private readonly InputAction m_gamecontroler_ShootLeft;
    public struct GamecontrolerActions
    {
        private @GamepadControler m_Wrapper;
        public GamecontrolerActions(@GamepadControler wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_gamecontroler_Move;
        public InputAction @Jump => m_Wrapper.m_gamecontroler_Jump;
        public InputAction @ShootRight => m_Wrapper.m_gamecontroler_ShootRight;
        public InputAction @ShootLeft => m_Wrapper.m_gamecontroler_ShootLeft;
        public InputActionMap Get() { return m_Wrapper.m_gamecontroler; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GamecontrolerActions set) { return set.Get(); }
        public void SetCallbacks(IGamecontrolerActions instance)
        {
            if (m_Wrapper.m_GamecontrolerActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_GamecontrolerActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_GamecontrolerActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_GamecontrolerActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_GamecontrolerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_GamecontrolerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_GamecontrolerActionsCallbackInterface.OnJump;
                @ShootRight.started -= m_Wrapper.m_GamecontrolerActionsCallbackInterface.OnShootRight;
                @ShootRight.performed -= m_Wrapper.m_GamecontrolerActionsCallbackInterface.OnShootRight;
                @ShootRight.canceled -= m_Wrapper.m_GamecontrolerActionsCallbackInterface.OnShootRight;
                @ShootLeft.started -= m_Wrapper.m_GamecontrolerActionsCallbackInterface.OnShootLeft;
                @ShootLeft.performed -= m_Wrapper.m_GamecontrolerActionsCallbackInterface.OnShootLeft;
                @ShootLeft.canceled -= m_Wrapper.m_GamecontrolerActionsCallbackInterface.OnShootLeft;
            }
            m_Wrapper.m_GamecontrolerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @ShootRight.started += instance.OnShootRight;
                @ShootRight.performed += instance.OnShootRight;
                @ShootRight.canceled += instance.OnShootRight;
                @ShootLeft.started += instance.OnShootLeft;
                @ShootLeft.performed += instance.OnShootLeft;
                @ShootLeft.canceled += instance.OnShootLeft;
            }
        }
    }
    public GamecontrolerActions @gamecontroler => new GamecontrolerActions(this);

    // ClavierSouris
    private readonly InputActionMap m_ClavierSouris;
    private IClavierSourisActions m_ClavierSourisActionsCallbackInterface;
    private readonly InputAction m_ClavierSouris_FoudrePouvoir;
    public struct ClavierSourisActions
    {
        private @GamepadControler m_Wrapper;
        public ClavierSourisActions(@GamepadControler wrapper) { m_Wrapper = wrapper; }
        public InputAction @FoudrePouvoir => m_Wrapper.m_ClavierSouris_FoudrePouvoir;
        public InputActionMap Get() { return m_Wrapper.m_ClavierSouris; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ClavierSourisActions set) { return set.Get(); }
        public void SetCallbacks(IClavierSourisActions instance)
        {
            if (m_Wrapper.m_ClavierSourisActionsCallbackInterface != null)
            {
                @FoudrePouvoir.started -= m_Wrapper.m_ClavierSourisActionsCallbackInterface.OnFoudrePouvoir;
                @FoudrePouvoir.performed -= m_Wrapper.m_ClavierSourisActionsCallbackInterface.OnFoudrePouvoir;
                @FoudrePouvoir.canceled -= m_Wrapper.m_ClavierSourisActionsCallbackInterface.OnFoudrePouvoir;
            }
            m_Wrapper.m_ClavierSourisActionsCallbackInterface = instance;
            if (instance != null)
            {
                @FoudrePouvoir.started += instance.OnFoudrePouvoir;
                @FoudrePouvoir.performed += instance.OnFoudrePouvoir;
                @FoudrePouvoir.canceled += instance.OnFoudrePouvoir;
            }
        }
    }
    public ClavierSourisActions @ClavierSouris => new ClavierSourisActions(this);
    public interface IGamecontrolerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnShootRight(InputAction.CallbackContext context);
        void OnShootLeft(InputAction.CallbackContext context);
    }
    public interface IClavierSourisActions
    {
        void OnFoudrePouvoir(InputAction.CallbackContext context);
    }
}
